language: python

matrix:
  include:
    - python: pypy
      env: LIBYAML="true"
    - python: pypy
      env: LIBYAML="false"
    - python: pypy3
      env: LIBYAML="false"
    - python: pypy3
      env: LIBYAML="true"
    - python: 2.7
      env: LIBYAML="false"
    - python: 2.7
      env: LIBYAML="true"
    - python: 3.5
      env: LIBYAML="false"
    - python: 3.5
      env: LIBYAML="true"
    - python: 3.6
      env: LIBYAML="false"
    - python: 3.6
      env: LIBYAML="true"
    - python: 3.7
      dist: xenial
      sudo: true
      env: LIBYAML="false"
    - python: 3.7
      dist: xenial
      sudo: true
      env: LIBYAML="true"

install:
  - pip install -q testtools fixtures
  - if [[ $LIBYAML == 'true' ]]; then sudo apt-get -qq install libyaml-dev; fi
  - python setup.py -q install

script:
  - python setup.py -q test
